language: C
sudo: true
dist: trusty
group: edge
install:
  - ./setup
script:
  - cd ./firmware/default/
  - ./build HelloWorld
  - ls ./bin/HelloWorld/HelloWorld.elf
  - ls ./bin/HelloWorld/HelloWorld.hex
  - ls ./bin/HelloWorld/HelloWorld.lst
  - ls ./bin/HelloWorld/HelloWorld.map
  - cd ../../
  - gdbgui &
  - wget http://127.0.0.1:5000
  - cd tools/Telemetry
  - ./telemetry &
  - wget http://127.0.0.1:5001
# after_success: